// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package types

import "encoding/json"

type AcademicYear struct {
	Id              int    `json:"id"`
	Code            string `json:"code"`
	BeginDate       string `json:"beginDate"`
	EndDate         string `json:"endDate"`
	IsOpenForPublic bool   `json:"isOpenForPublic"`
}

type Agreement struct {
	Name                 string `json:"name"`
	Type                 string `json:"type"`
	PublishDate          string `json:"publishDate"`
	ReceivingInstitution string `json:"receivingInstitution"`
	SendingInstitution   string `json:"sendingInstitution"`
	Articulation         string `json:"articulation"`
}

type AgreementList struct {
	AcademicYearId         int             `json:"academicYearId"`
	ReceivingInstitutionId int             `json:"receivingInstitutionId"`
	SendingInstitutionId   int             `json:"sendingInstitutionId"`
	Agreements             json.RawMessage `json:"agreements"`
}

type Course struct {
	CourseIdentifierParentId int             `json:"courseIdentifierParentId"`
	CourseParentId           int             `json:"courseParentId"`
	CourseTitle              string          `json:"courseTitle"`
	CourseNumber             string          `json:"courseNumber"`
	Prefix                   string          `json:"prefix"`
	PrefixParentId           int             `json:"prefixParentId"`
	Department               string          `json:"department"`
	MinUnits                 float64         `json:"minUnits"`
	MaxUnits                 float64         `json:"maxUnits"`
	Begin                    json.RawMessage `json:"begin"`
	End                      json.RawMessage `json:"end"`
}

type CourseTransferability struct {
	Course       json.RawMessage `json:"course"`
	CsugeAreas   json.RawMessage `json:"csugeAreas"`
	IgetcAreas   json.RawMessage `json:"igetcAreas"`
	CsuaiAreas   json.RawMessage `json:"csuaiAreas"`
	CalgetcAreas json.RawMessage `json:"calgetcAreas"`
	UctelAreas   json.RawMessage `json:"uctelAreas"`
}

type Department struct {
	Id                  int             `json:"id"`
	ParentId            int             `json:"parentId"`
	InstitutionParentId int             `json:"institutionParentId"`
	Code                string          `json:"code"`
	Description         string          `json:"description"`
	Begin               json.RawMessage `json:"begin"`
	End                 json.RawMessage `json:"end"`
}

type DepartmentArticulation struct {
	Type   string          `json:"type"`
	Course json.RawMessage `json:"course"`
	Key    string          `json:"key"`
}

type DepartmentResult struct {
	AcademicYearId      int             `json:"academicYearId"`
	InstitutionParentId int             `json:"institutionParentId"`
	Departments         json.RawMessage `json:"departments"`
}

type Institution struct {
	Id                    int             `json:"id"`
	Code                  string          `json:"code"`
	Names                 json.RawMessage `json:"names"`
	IsCommunityCollege    bool            `json:"isCommunityCollege"`
	Category              int             `json:"category"`
	TermTypeAcademicYears json.RawMessage `json:"termTypeAcademicYears"`
}

type InstitutionAgreement struct {
	InstitutionId    int             `json:"institutionId"`
	ReceivingYearIds json.RawMessage `json:"receivingYearIds"`
	SendingYearIds   json.RawMessage `json:"sendingYearIds"`
}

type MajorArticulation struct {
	Name          string          `json:"name"`
	Articulations json.RawMessage `json:"articulations"`
	Key           string          `json:"key"`
}

type Prefix struct {
	Id             int             `json:"id"`
	PrefixParentId int             `json:"prefixParentId"`
	InstitutionId  int             `json:"institutionId"`
	Code           string          `json:"code"`
	Description    string          `json:"description"`
	Begin          json.RawMessage `json:"begin"`
	End            json.RawMessage `json:"end"`
}

type TransferabilityArea struct {
	Id          int    `json:"id"`
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type TransferabilityAreaCourses struct {
	Id          int             `json:"id"`
	Code        string          `json:"code"`
	Description string          `json:"description"`
	Courses     json.RawMessage `json:"courses"`
}

type YearTerm struct {
	Id           int    `json:"id"`
	Code         string `json:"code"`
	YearTermCode string `json:"yearTermCode"`
	Description  string `json:"description"`
	BeginDate    string `json:"beginDate"`
	EndDate      string `json:"endDate"`
}
