// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package mcp

import (
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"math"
	"net/url"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"github.com/johnnyrobot/assist-pp-cli/internal/cli"
	"github.com/johnnyrobot/assist-pp-cli/internal/client"
	"github.com/johnnyrobot/assist-pp-cli/internal/cliutil"
	"github.com/johnnyrobot/assist-pp-cli/internal/config"
	"github.com/johnnyrobot/assist-pp-cli/internal/learn"
	"github.com/johnnyrobot/assist-pp-cli/internal/mcp/bound"
	"github.com/johnnyrobot/assist-pp-cli/internal/mcp/cobratree"
	"github.com/johnnyrobot/assist-pp-cli/internal/store"
	mcplib "github.com/mark3labs/mcp-go/mcp"
	"github.com/mark3labs/mcp-go/server"
)

const (
	// MCP hosts can fan out tool calls faster than a human CLI session.
	// Keep them on the same polite-client limiter path instead of disabling
	// pacing with rate=0; users can still tune human CLI calls with --rate-limit.
	defaultMCPRateLimit = 2
)

// RegisterTools registers all API operations as MCP tools.
func RegisterTools(s *server.MCPServer) {
	registerPublicEndpointTools(s)
	// Retain the generated licensed-API registrations below as unreachable
	// source context for future regeneration only. The runnable MCP surface is
	// public assist.org routes plus the Cobra command mirror.
	if false {
		s.AddTool(
			mcplib.NewTool("academic-years_list",
				mcplib.WithDescription("List active academic years. Returns array of AcademicYear."),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/AcademicYears/api", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
		)
		s.AddTool(
			mcplib.NewTool("agreements_department-by-course",
				mcplib.WithDescription("Find department articulations containing a course. Required: sending-institution-parent-id, receiving-institution-parent-id, course-type, course-identifier-parent-id, academic-year-id. Optional: term-id. Returns array of DepartmentArticulation."),
				mcplib.WithNumber("sending-institution-parent-id", mcplib.Required(), mcplib.Description("Sending institution parent ID.")),
				mcplib.WithNumber("receiving-institution-parent-id", mcplib.Required(), mcplib.Description("Receiving institution parent ID.")),
				mcplib.WithString("course-type", mcplib.Required(), mcplib.Description("Institution side that owns the course ID.")),
				mcplib.WithNumber("course-identifier-parent-id", mcplib.Required(), mcplib.Description("Course identifier parent ID to find.")),
				mcplib.WithNumber("academic-year-id", mcplib.Required(), mcplib.Description("Academic year ID returned by academic-years list.")),
				mcplib.WithNumber("term-id", mcplib.Description("Optional midyear term ID for sending-course matching.")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/articulation/api/Agreements/Department/from/{sendingInstitutionParentId}/to/{receivingInstitutionParentId}/{courseType}/course/{courseIdentifierParentId}/for/{academicYearId}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sending-institution-parent-id", WireName: "sendingInstitutionParentId", Location: "path"}, {PublicName: "receiving-institution-parent-id", WireName: "receivingInstitutionParentId", Location: "path"}, {PublicName: "course-type", WireName: "courseType", Location: "path"}, {PublicName: "course-identifier-parent-id", WireName: "courseIdentifierParentId", Location: "path"}, {PublicName: "academic-year-id", WireName: "academicYearId", Location: "path"}, {PublicName: "term-id", WireName: "termId", Location: "query"}}, []string{"sendingInstitutionParentId", "receivingInstitutionParentId", "courseType", "courseIdentifierParentId", "academicYearId"}),
		)
		s.AddTool(
			mcplib.NewTool("agreements_get",
				mcplib.WithDescription("Get a published agreement by its URL-encoded composite key. Required: key. Returns the Agreement."),
				mcplib.WithString("key", mcplib.Required(), mcplib.Description("Composite agreement key returned by agreements list.")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/articulation/api/Agreements", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "key", WireName: "Key", Location: "query"}}, []string{}),
		)
		s.AddTool(
			mcplib.NewTool("agreements_institutions",
				mcplib.WithDescription("List institutions that have published agreements with an institution. Required: institution-id. Returns array of InstitutionAgreement."),
				mcplib.WithNumber("institution-id", mcplib.Required(), mcplib.Description("Institution ID used to find agreement partners.")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/articulation/api/Agreements/Published/from/{institutionId}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "institution-id", WireName: "institutionId", Location: "path"}}, []string{"institutionId"}),
		)
		s.AddTool(
			mcplib.NewTool("agreements_list",
				mcplib.WithDescription("List published agreements for an institution pair, year, and type. Required: receiving-institution-id, sending-institution-id, academic-year-id, types. Returns the AgreementList."),
				mcplib.WithNumber("receiving-institution-id", mcplib.Required(), mcplib.Description("Receiving UC, CSU, or independent institution ID.")),
				mcplib.WithNumber("sending-institution-id", mcplib.Required(), mcplib.Description("Sending institution ID.")),
				mcplib.WithNumber("academic-year-id", mcplib.Required(), mcplib.Description("Academic year ID returned by academic-years list.")),
				mcplib.WithString("types", mcplib.Required(), mcplib.Description("Agreement type to list.")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/articulation/api/Agreements/Published/for/{receivingInstitutionId}/to/{sendingInstitutionId}/in/{academicYearId}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "receiving-institution-id", WireName: "receivingInstitutionId", Location: "path"}, {PublicName: "sending-institution-id", WireName: "sendingInstitutionId", Location: "path"}, {PublicName: "academic-year-id", WireName: "academicYearId", Location: "path"}, {PublicName: "types", WireName: "types", Location: "query"}}, []string{"receivingInstitutionId", "sendingInstitutionId", "academicYearId"}),
		)
		s.AddTool(
			mcplib.NewTool("agreements_major-by-course",
				mcplib.WithDescription("Find major articulations containing a course. Required: sending-institution-parent-id, receiving-institution-parent-id, course-type, course-identifier-parent-id, academic-year-id. Optional: term-id. Returns array of MajorArticulation."),
				mcplib.WithNumber("sending-institution-parent-id", mcplib.Required(), mcplib.Description("Sending institution parent ID.")),
				mcplib.WithNumber("receiving-institution-parent-id", mcplib.Required(), mcplib.Description("Receiving institution parent ID.")),
				mcplib.WithString("course-type", mcplib.Required(), mcplib.Description("Institution side that owns the course ID.")),
				mcplib.WithNumber("course-identifier-parent-id", mcplib.Required(), mcplib.Description("Course identifier parent ID to find.")),
				mcplib.WithNumber("academic-year-id", mcplib.Required(), mcplib.Description("Academic year ID returned by academic-years list.")),
				mcplib.WithNumber("term-id", mcplib.Description("Optional midyear term ID for sending-course matching.")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/articulation/api/Agreements/Major/from/{sendingInstitutionParentId}/to/{receivingInstitutionParentId}/{courseType}/course/{courseIdentifierParentId}/for/{academicYearId}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "sending-institution-parent-id", WireName: "sendingInstitutionParentId", Location: "path"}, {PublicName: "receiving-institution-parent-id", WireName: "receivingInstitutionParentId", Location: "path"}, {PublicName: "course-type", WireName: "courseType", Location: "path"}, {PublicName: "course-identifier-parent-id", WireName: "courseIdentifierParentId", Location: "path"}, {PublicName: "academic-year-id", WireName: "academicYearId", Location: "path"}, {PublicName: "term-id", WireName: "termId", Location: "query"}}, []string{"sendingInstitutionParentId", "receivingInstitutionParentId", "courseType", "courseIdentifierParentId", "academicYearId"}),
		)
		s.AddTool(
			mcplib.NewTool("courses_by-ids",
				mcplib.WithDescription("Get courses by course identifier parent IDs. Required: institution-id, academic-year-id. Returns array of Course."),
				mcplib.WithNumber("institution-id", mcplib.Required(), mcplib.Description("Institution ID returned by institutions list.")),
				mcplib.WithNumber("academic-year-id", mcplib.Required(), mcplib.Description("Academic year ID returned by academic-years list.")),
				mcplib.WithString("body_json", mcplib.Required(), mcplib.Description("Request body as a JSON array of course identifier parent IDs, for example [340948,340950]")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("POST", "/Courses/api/Institution/{institutionId}/Year/{academicYearId}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "institution-id", WireName: "institutionId", Location: "path"}, {PublicName: "academic-year-id", WireName: "academicYearId", Location: "path"}, {PublicName: "body_json", WireName: "body_json", Location: "body_json", BodyIsArray: true}}, []string{"institutionId", "academicYearId"}),
		)
		s.AddTool(
			mcplib.NewTool("courses_list",
				mcplib.WithDescription("List or filter courses for an institution and academic year. Required: institution-id, academic-year-id. Optional: filter, department, department-parent-id (plus 2 more). Returns array of Course."),
				mcplib.WithNumber("institution-id", mcplib.Required(), mcplib.Description("Institution ID returned by institutions list.")),
				mcplib.WithNumber("academic-year-id", mcplib.Required(), mcplib.Description("Academic year ID returned by academic-years list.")),
				mcplib.WithString("filter", mcplib.Description("Partial prefix, number, prefix-number, or course-title match.")),
				mcplib.WithString("department", mcplib.Description("Exact department description to filter by.")),
				mcplib.WithNumber("department-parent-id", mcplib.Description("Department parent ID returned by departments list.")),
				mcplib.WithString("prefix", mcplib.Description("Exact course prefix such as CHEM.")),
				mcplib.WithNumber("prefix-parent-id", mcplib.Description("Prefix parent ID returned by prefixes list.")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/Courses/api/Institution/{institutionId}/Year/{academicYearId}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "institution-id", WireName: "institutionId", Location: "path"}, {PublicName: "academic-year-id", WireName: "academicYearId", Location: "path"}, {PublicName: "filter", WireName: "filter", Location: "query"}, {PublicName: "department", WireName: "department", Location: "query"}, {PublicName: "department-parent-id", WireName: "departmentParentId", Location: "query"}, {PublicName: "prefix", WireName: "prefix", Location: "query"}, {PublicName: "prefix-parent-id", WireName: "prefixParentId", Location: "query"}}, []string{"institutionId", "academicYearId"}),
		)
		s.AddTool(
			mcplib.NewTool("departments_list",
				mcplib.WithDescription("List departments for an institution and academic year. Required: institution-id, academic-year-id. Optional: include-terminated (default: false). Returns array of Department."),
				mcplib.WithNumber("institution-id", mcplib.Required(), mcplib.Description("Institution ID returned by institutions list.")),
				mcplib.WithNumber("academic-year-id", mcplib.Required(), mcplib.Description("Academic year ID returned by academic-years list.")),
				mcplib.WithBoolean("include-terminated", mcplib.Description("Include departments terminated by the selected year.")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/Departments/api/Institution/{institutionId}/Year/{academicYearId}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "institution-id", WireName: "institutionId", Location: "path"}, {PublicName: "academic-year-id", WireName: "academicYearId", Location: "path"}, {PublicName: "include-terminated", WireName: "includeTerminated", Location: "query", Default: "false"}}, []string{"institutionId", "academicYearId"}),
		)
		s.AddTool(
			mcplib.NewTool("departments_search",
				mcplib.WithDescription("Search departments across institutions and academic years. Returns array of DepartmentResult."),
				mcplib.WithString("body_json", mcplib.Required(), mcplib.Description("Request body as a JSON object string (this endpoint accepts a polymorphic schema: oneOf/anyOf)")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("POST", "/Departments/api", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "body_json", WireName: "body_json", Location: "body_json"}}, []string{}),
		)
		s.AddTool(
			mcplib.NewTool("institutions_list",
				mcplib.WithDescription("List all institutions. Returns array of Institution."),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/Institutions/api", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
		)
		s.AddTool(
			mcplib.NewTool("prefixes_list",
				mcplib.WithDescription("List course prefixes for an institution and academic year. Required: institution-id, academic-year-id. Optional: include-terminated (default: false). Returns array of Prefix."),
				mcplib.WithNumber("institution-id", mcplib.Required(), mcplib.Description("Institution ID returned by institutions list.")),
				mcplib.WithNumber("academic-year-id", mcplib.Required(), mcplib.Description("Academic year ID returned by academic-years list.")),
				mcplib.WithBoolean("include-terminated", mcplib.Description("Include prefixes terminated by the selected year.")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/Prefixes/api/Institution/{institutionId}/Year/{academicYearId}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "institution-id", WireName: "institutionId", Location: "path"}, {PublicName: "academic-year-id", WireName: "academicYearId", Location: "path"}, {PublicName: "include-terminated", WireName: "includeTerminated", Location: "query", Default: "false"}}, []string{"institutionId", "academicYearId"}),
		)
		s.AddTool(
			mcplib.NewTool("transferability_areas",
				mcplib.WithDescription("List transferability areas for a type and academic year. Required: area-type, academic-year-id. Returns array of TransferabilityArea."),
				mcplib.WithString("area-type", mcplib.Required(), mcplib.Description("Transferability area type code.")),
				mcplib.WithNumber("academic-year-id", mcplib.Required(), mcplib.Description("Academic year ID returned by academic-years list.")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/Transferability/api/{areaType}/Year/{academicYearId}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "area-type", WireName: "areaType", Location: "path"}, {PublicName: "academic-year-id", WireName: "academicYearId", Location: "path"}}, []string{"areaType", "academicYearId"}),
		)
		s.AddTool(
			mcplib.NewTool("transferability_course",
				mcplib.WithDescription("Get one course and every transferability area it satisfies. Required: course-identifier-parent-id, institution-id, academic-year-id. Returns the CourseTransferability."),
				mcplib.WithNumber("course-identifier-parent-id", mcplib.Required(), mcplib.Description("Course identifier parent ID returned by courses list.")),
				mcplib.WithNumber("institution-id", mcplib.Required(), mcplib.Description("Institution ID returned by institutions list.")),
				mcplib.WithNumber("academic-year-id", mcplib.Required(), mcplib.Description("Academic year ID returned by academic-years list.")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/Transferability/api/Courses/{courseIdentifierParentId}/Institution/{institutionId}/Year/{academicYearId}", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "course-identifier-parent-id", WireName: "courseIdentifierParentId", Location: "path"}, {PublicName: "institution-id", WireName: "institutionId", Location: "path"}, {PublicName: "academic-year-id", WireName: "academicYearId", Location: "path"}}, []string{"courseIdentifierParentId", "institutionId", "academicYearId"}),
		)
		s.AddTool(
			mcplib.NewTool("transferability_courses",
				mcplib.WithDescription("List transferability areas and satisfying courses for an institution and year. Returns array of TransferabilityAreaCourses."),
				mcplib.WithString("body_json", mcplib.Required(), mcplib.Description("Request body as a JSON object string (this endpoint accepts a polymorphic schema: oneOf/anyOf)")),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("POST", "/Transferability/api/Courses", true, false, nil, mcpPageConfig{}, []mcpParamBinding{{PublicName: "body_json", WireName: "body_json", Location: "body_json"}}, []string{}),
		)
		s.AddTool(
			mcplib.NewTool("year-terms_list",
				mcplib.WithDescription("List all year terms. Returns array of YearTerm."),
				mcplib.WithReadOnlyHintAnnotation(true),
				mcplib.WithDestructiveHintAnnotation(false),
				mcplib.WithOpenWorldHintAnnotation(true),
			),
			makeAPIHandler("GET", "/YearTerms/api", true, false, nil, mcpPageConfig{}, []mcpParamBinding{}, []string{}),
		)
	}
	// Search tool — faster than iterating list endpoints for finding specific items
	s.AddTool(
		mcplib.NewTool("search",
			mcplib.WithDescription("Full-text search across all synced data. Faster than paginating list endpoints. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("Search query (supports FTS5 syntax: AND, OR, NOT, quotes for phrases)")),
			mcplib.WithNumber("limit", mcplib.Description("Max results (default 25)")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSearch,
	)
	// SQL tool — ad-hoc analysis on synced data without API calls
	s.AddTool(
		mcplib.NewTool("sql",
			mcplib.WithDescription("Run read-only SQL against local database. Use for ad-hoc analysis, aggregations, and joins across synced resources. Requires sync first."),
			mcplib.WithString("query", mcplib.Required(), mcplib.Description("SQL query (SELECT or WITH...SELECT). Synced records live in resources(resource_type, id, data); filter by resource_type and use json_extract on data, e.g. SELECT json_extract(data,'$.name') FROM resources WHERE resource_type='academic-years'.")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleSQL,
	)

	// Context tool — front-loaded domain knowledge for agents.
	// Call this first to understand the API taxonomy, query patterns, and capabilities.
	s.AddTool(
		mcplib.NewTool("context",
			mcplib.WithDescription("Get API domain context: resource taxonomy, auth requirements, query tips, and unique capabilities. Call this first."),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
		),
		handleContext,
	)

	// Runtime Cobra-tree mirror — exposes every user-facing command that is
	// not already covered by a typed endpoint or framework MCP tool.
	cobratree.RegisterAll(s, cli.RootCmd(), cobratree.SiblingCLIPath)
}

func registerPublicEndpointTools(s *server.MCPServer) {
	readAnnotations := []mcplib.ToolOption{
		mcplib.WithReadOnlyHintAnnotation(true),
		mcplib.WithDestructiveHintAnnotation(false),
		mcplib.WithOpenWorldHintAnnotation(true),
	}
	add := func(name, description, path string, options []mcplib.ToolOption, bindings []mcpParamBinding, requiredPath []string) {
		options = append(options, readAnnotations...)
		s.AddTool(mcplib.NewTool(name, append([]mcplib.ToolOption{mcplib.WithDescription(description)}, options...)...), makeAPIHandler("GET", path, true, false, nil, mcpPageConfig{}, bindings, requiredPath))
	}
	add("settings_get", "Get public ASSIST application settings and version limits.", "/api/appsettings", nil, nil, nil)
	add("academic-years_list", "List public ASSIST academic years.", "/api/AcademicYears", nil, nil, nil)
	add("institutions_list", "List public ASSIST institutions.", "/api/institutions", nil, nil, nil)
	add("agreements_get", "Get a public articulation agreement by composite key.", "/api/articulation/Agreements",
		[]mcplib.ToolOption{mcplib.WithString("key", mcplib.Required(), mcplib.Description("Composite agreement key."))},
		[]mcpParamBinding{{PublicName: "key", WireName: "Key", Location: "query"}}, nil)
	add("agreements_categories", "List public agreement categories for an institution pair and year.", "/api/agreements/categories",
		[]mcplib.ToolOption{
			mcplib.WithNumber("receiving-institution-id", mcplib.Required()),
			mcplib.WithNumber("sending-institution-id", mcplib.Required()),
			mcplib.WithNumber("academic-year-id", mcplib.Required()),
		},
		[]mcpParamBinding{
			{PublicName: "receiving-institution-id", WireName: "receivingInstitutionId", Location: "query"},
			{PublicName: "sending-institution-id", WireName: "sendingInstitutionId", Location: "query"},
			{PublicName: "academic-year-id", WireName: "academicYearId", Location: "query"},
		}, nil)
	add("agreements_institutions", "List public agreement partners for a sending institution.", "/api/institutions/{institutionId}/agreements",
		[]mcplib.ToolOption{mcplib.WithNumber("institution-id", mcplib.Required())},
		[]mcpParamBinding{
			{PublicName: "institution-id", WireName: "institutionId", Location: "path"},
			{PublicName: "as-sending-only", WireName: "asSendingOnly", Location: "query", Default: "true"},
		}, []string{"institutionId"})
	s.AddTool(
		mcplib.NewTool("agreements_list",
			mcplib.WithDescription("List public agreements for an institution pair, year, and category."),
			mcplib.WithNumber("receiving-institution-id", mcplib.Required()),
			mcplib.WithNumber("sending-institution-id", mcplib.Required()),
			mcplib.WithNumber("academic-year-id", mcplib.Required()),
			mcplib.WithString("types", mcplib.Required(), mcplib.Description("Prefix, Department, Major, or GeneralEducation")),
			mcplib.WithReadOnlyHintAnnotation(true),
			mcplib.WithDestructiveHintAnnotation(false),
			mcplib.WithOpenWorldHintAnnotation(true),
		),
		handlePublicAgreementsList,
	)
	add("transferability_years", "List public transferability academic years for an institution.", "/api/institutions/{institutionId}/transferability/availableAcademicYears",
		[]mcplib.ToolOption{mcplib.WithNumber("institution-id", mcplib.Required())},
		[]mcpParamBinding{{PublicName: "institution-id", WireName: "institutionId", Location: "path"}}, []string{"institutionId"})
	transferOptions := []mcplib.ToolOption{
		mcplib.WithNumber("institution-id", mcplib.Required()),
		mcplib.WithNumber("academic-year-id", mcplib.Required()),
		mcplib.WithString("list-type", mcplib.Required()),
	}
	transferBindings := []mcpParamBinding{
		{PublicName: "institution-id", WireName: "institutionId", Location: "query"},
		{PublicName: "academic-year-id", WireName: "academicYearId", Location: "query"},
		{PublicName: "list-type", WireName: "listType", Location: "query"},
	}
	add("transferability_categories", "List public transferability grouping categories.", "/api/transferability/categories", transferOptions, transferBindings, nil)
	add("transferability_courses", "Fetch public transferability course data.", "/api/transferability/courses", transferOptions, transferBindings, nil)
}

func handlePublicAgreementsList(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	receiving := formatMCPParamValue(args["receiving-institution-id"])
	sending := formatMCPParamValue(args["sending-institution-id"])
	year := formatMCPParamValue(args["academic-year-id"])
	category := formatMCPParamValue(args["types"])
	switch category {
	case "Prefix":
		category = "prefix"
	case "Department":
		category = "dept"
	case "Major":
		category = "major"
	case "GeneralEducation":
		category = "breadth"
	default:
		return mcplib.NewToolResultError("types must be Prefix, Department, Major, or GeneralEducation"), nil
	}
	// Preserve the browser application's parameter order. ASSIST currently
	// returns an empty report set when these same keys are alphabetically
	// reordered.
	path := "/api/agreements?receivingInstitutionId=" + url.QueryEscape(receiving) +
		"&sendingInstitutionId=" + url.QueryEscape(sending) +
		"&academicYearId=" + url.QueryEscape(year) +
		"&categoryCode=" + url.QueryEscape(category)
	c, err := newMCPClient()
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	data, err := c.Get(ctx, path, nil)
	if err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}
	return mcpToolResultText("GET", data), nil
}

type mcpParamBinding struct {
	PublicName  string
	WireName    string
	Location    string
	Default     string
	BodyIsArray bool
}

type mcpPageConfig struct {
	CursorParam    string
	NextCursorPath string
}

// validateMCPBodyJSON preserves ASSIST's one official top-level array request
// alongside the generator's object-body fallback contract.
func validateMCPBodyJSON(raw string, allowArray bool) error {
	var parsed any
	if err := json.Unmarshal([]byte(raw), &parsed); err != nil {
		return fmt.Errorf("body_json must be valid JSON: %w", err)
	}
	if allowArray {
		if _, ok := parsed.([]any); !ok {
			return fmt.Errorf("body_json must be a JSON array, got JSON %T", parsed)
		}
		return nil
	}
	if _, ok := parsed.(map[string]any); !ok {
		return fmt.Errorf("body_json must be a JSON object, got JSON %T", parsed)
	}
	return nil
}

func formatMCPParamValue(v any) string {
	switch tv := v.(type) {
	case string:
		return tv
	case bool:
		return strconv.FormatBool(tv)
	case float64:
		if math.IsNaN(tv) || math.IsInf(tv, 0) {
			return strconv.FormatFloat(tv, 'f', -1, 64)
		}
		if math.Trunc(tv) == tv && math.Abs(tv) < 1e15 {
			return strconv.FormatInt(int64(tv), 10)
		}
		return strconv.FormatFloat(tv, 'f', -1, 64)
	case float32:
		f := float64(tv)
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return strconv.FormatFloat(f, 'f', -1, 32)
		}
		if math.Trunc(f) == f && math.Abs(f) < 1e15 {
			return strconv.FormatInt(int64(f), 10)
		}
		return strconv.FormatFloat(f, 'f', -1, 32)
	default:
		// Composite values (a native []any / map[string]any from an array or
		// object param) reach this path when bound to a query or path slot;
		// JSON-encode them so the wire value is valid JSON rather than Go's
		// "[a b c]" / "map[...]" rendering. Body params never come through
		// here — they are stored natively in bodyArgs and marshalled there.
		if b, err := json.Marshal(v); err == nil {
			return string(b)
		}
		return fmt.Sprintf("%v", v)
	}
}

// makeAPIHandler creates a generic MCP tool handler for an API endpoint.
func makeAPIHandler(method, pathTemplate string, readOnly bool, binaryResponse bool, headerOverrides map[string]string, pageConfig mcpPageConfig, bindings []mcpParamBinding, positionalParams []string) server.ToolHandlerFunc {
	return func(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
		c, err := newMCPClient()
		if err != nil {
			return mcplib.NewToolResultError(err.Error()), nil
		}

		// mcp-go v0.47+ made CallToolParams.Arguments an `any` to support
		// non-map payloads; GetArguments() returns the map[string]any shape
		// we rely on here (or an empty map when the payload is something else).
		args := req.GetArguments()

		// positionalParams mixes real URL path params with CLI positional
		// args that map to query params (e.g. `search <query>` -> ?query=);
		// the placeholder check below disambiguates them at runtime.
		path := pathTemplate
		knownArgs := make(map[string]bool, len(bindings))
		pathParams := make(map[string]bool, len(positionalParams))
		params := make(map[string]string)
		bodyArgs := make(map[string]any)
		mcpCursor := ""
		if pageConfig.CursorParam != "" {
			knownArgs["cursor"] = true
			if v, ok := args["cursor"]; ok {
				s, ok := v.(string)
				if !ok {
					return mcplib.NewToolResultError("cursor must be an opaque string returned by a previous MCP response"), nil
				}
				mcpCursor = s
				upstreamCursor, err := bound.UpstreamCursor(s)
				if err != nil {
					return mcplib.NewToolResultError(err.Error()), nil
				}
				if upstreamCursor != "" {
					params[pageConfig.CursorParam] = upstreamCursor
				}
			}
		}
		var headers map[string]string
		if len(headerOverrides) > 0 {
			headers = make(map[string]string, len(headerOverrides)+1)
			for k, v := range headerOverrides {
				headers[k] = v
			}
		}
		if binaryResponse {
			if headers == nil {
				headers = map[string]string{}
			}
			headers[client.BinaryResponseHeader] = "true"
		}
		// bodyJSONOverride holds an opaque body for endpoints whose request
		// schema is a oneOf/anyOf and was wired with a single body_json input.
		// When set, it replaces the bodyArgs map for POST/PUT/PATCH.
		var bodyJSONOverride json.RawMessage
		for _, binding := range bindings {
			knownArgs[binding.PublicName] = true
			v, ok := args[binding.PublicName]
			if !ok {
				if binding.Default != "" {
					v = binding.Default
				} else {
					continue
				}
			}
			switch binding.Location {
			case "path":
				placeholder := "{" + binding.WireName + "}"
				pathParams[binding.PublicName] = true
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			case "body":
				bodyArgs[binding.WireName] = v
			case "body_json":
				if s, ok := v.(string); ok && s != "" {
					if err := validateMCPBodyJSON(s, binding.BodyIsArray); err != nil {
						return mcplib.NewToolResultError(err.Error()), nil
					}
					bodyJSONOverride = json.RawMessage(s)
				}
			default:
				params[binding.WireName] = formatMCPParamValue(v)
			}
		}
		for _, p := range positionalParams {
			placeholder := "{" + p + "}"
			if !strings.Contains(pathTemplate, placeholder) {
				continue
			}
			pathParams[p] = true
			if v, ok := args[p]; ok {
				path = strings.Replace(path, placeholder, formatMCPParamValue(v), 1)
			}
		}

		for k, v := range args {
			if pathParams[k] || knownArgs[k] {
				continue
			}
			switch method {
			case "POST", "PUT", "PATCH":
				bodyArgs[k] = v
			default:
				params[k] = formatMCPParamValue(v)
			}
		}

		var data json.RawMessage
		switch method {
		case "GET":
			if len(headers) > 0 {
				data, err = c.GetWithHeaders(ctx, path, params, headers)
				break
			}
			data, err = c.Get(ctx, path, params)
		case "POST":
			if len(bodyJSONOverride) > 0 {
				if len(headers) > 0 {
					if readOnly {
						data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					} else {
						data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					}
					break
				}
				if readOnly {
					data, _, err = c.PostQueryWithParams(ctx, path, params, bodyJSONOverride)
				} else {
					data, _, err = c.PostWithParams(ctx, path, params, bodyJSONOverride)
				}
				break
			}
			if len(headers) > 0 {
				if readOnly {
					data, _, err = c.PostQueryWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				} else {
					data, _, err = c.PostWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				}
				break
			}
			if readOnly {
				data, _, err = c.PostQueryWithParams(ctx, path, params, bodyArgs)
			} else {
				data, _, err = c.PostWithParams(ctx, path, params, bodyArgs)
			}
		case "PUT":
			if len(bodyJSONOverride) > 0 {
				if len(headers) > 0 {
					data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					break
				}
				data, _, err = c.PutWithParams(ctx, path, params, bodyJSONOverride)
				break
			}
			if len(headers) > 0 {
				data, _, err = c.PutWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PutWithParams(ctx, path, params, bodyArgs)
		case "PATCH":
			if len(bodyJSONOverride) > 0 {
				if len(headers) > 0 {
					data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyJSONOverride, headers)
					break
				}
				data, _, err = c.PatchWithParams(ctx, path, params, bodyJSONOverride)
				break
			}
			if len(headers) > 0 {
				data, _, err = c.PatchWithParamsAndHeaders(ctx, path, params, bodyArgs, headers)
				break
			}
			data, _, err = c.PatchWithParams(ctx, path, params, bodyArgs)
		case "DELETE":
			if len(headers) > 0 {
				data, _, err = c.DeleteWithParamsAndHeaders(ctx, path, params, headers)
				break
			}
			data, _, err = c.DeleteWithParams(ctx, path, params)
		default:
			return mcplib.NewToolResultError("unsupported method: " + method), nil
		}

		if err != nil {
			msg := err.Error()
			switch {
			case strings.Contains(msg, "HTTP 409"):
				return mcplib.NewToolResultText("already exists (no-op)"), nil
			case strings.Contains(msg, "HTTP 400") && cliutil.LooksLikeAuthError(msg):
				return mcplib.NewToolResultError("public-session error: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: ASSIST requires an anonymous XSRF bootstrap, not an API key. Run 'assist-pp-cli doctor' to check public connectivity."), nil
			case strings.Contains(msg, "HTTP 401"):
				return mcplib.NewToolResultError("unexpected authentication response from an anonymous public endpoint: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: no API key is used; run 'assist-pp-cli doctor'."), nil
			case strings.Contains(msg, "HTTP 403"):
				return mcplib.NewToolResultError("public endpoint denied the request: " + cliutil.SanitizeErrorBody(msg) +
					"\nhint: no API key is used; run 'assist-pp-cli doctor' and retry later."), nil
			case strings.Contains(msg, "HTTP 404"):
				if method == "DELETE" {
					return mcplib.NewToolResultText("already deleted (no-op)"), nil
				}
				return mcplib.NewToolResultError("not found: " + msg), nil
			case strings.Contains(msg, "HTTP 429"):
				return mcplib.NewToolResultError("rate limited: " + msg), nil
			default:
				return mcplib.NewToolResultError(msg), nil
			}
		}

		if binaryResponse {
			encoded := base64.StdEncoding.EncodeToString(data)
			out, err := json.Marshal(map[string]any{
				"content_encoding": "base64",
				"data_base64":      encoded,
				"byte_count":       len(data),
			})
			if err != nil {
				return mcplib.NewToolResultError(fmt.Sprintf("encoding binary result: %v", err)), nil
			}
			if len(out) > bound.MaxBytes {
				return mcplib.NewToolResultError(fmt.Sprintf("binary response is too large for MCP text output: %d response bytes encode to %d base64 bytes and %d MCP result bytes, exceeding the %d byte budget. Use the companion CLI command with --output <file> to save the payload locally.", len(data), len(encoded), len(out), bound.MaxBytes)), nil
			}
			return mcplib.NewToolResultText(string(out)), nil
		}
		if pageConfig.CursorParam != "" {
			return mcpToolPageResultText(method, data, pageConfig, mcpCursor), nil
		}
		return mcpToolResultText(method, data), nil
	}
}

func mcpToolResultText(method string, data json.RawMessage) *mcplib.CallToolResult {
	return mcplib.NewToolResultText(bound.EndpointResponse(method, data))
}

func mcpToolPageResultText(method string, data json.RawMessage, pageConfig mcpPageConfig, cursor string) *mcplib.CallToolResult {
	return mcplib.NewToolResultText(bound.EndpointPageResponse(method, data, bound.PageOptions{
		Cursor:         cursor,
		CursorParam:    pageConfig.CursorParam,
		NextCursorPath: pageConfig.NextCursorPath,
	}))
}

func newMCPClient() (*client.Client, error) {
	cfg, err := newMCPConfig()
	if err != nil {
		return nil, err
	}
	return newMCPClientFromConfig(cfg), nil
}

func newMCPConfig() (*config.Config, error) {
	cfg, err := config.Load("")
	if err != nil {
		return nil, fmt.Errorf("loading config: %w", err)
	}
	return cfg, nil
}

func newMCPClientFromConfig(cfg *config.Config) *client.Client {
	c := client.New(cfg, 60*time.Second, defaultMCPRateLimit)
	// Agents calling through MCP need fresh data every call. The on-disk
	// response cache survives across MCP server invocations, so a
	// DELETE/PATCH followed by a GET would otherwise return the
	// pre-mutation snapshot for up to the cache TTL. The interactive CLI
	// constructs its own client and is unaffected.
	c.NoCache = true
	return c
}

func mcpDBPath() (string, error) {
	dir, err := cliutil.DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "data.db"), nil
}

type mcpStoreStatusKind string

const (
	mcpStoreStatusEmpty mcpStoreStatusKind = "empty"
	mcpStoreStatusReady mcpStoreStatusKind = "ready"
)

func openMCPReadOnlyStore(path string) (*store.Store, *mcplib.CallToolResult) {
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil, mcplib.NewToolResultError(mcpMissingStoreMessage(path))
		}
		return nil, mcplib.NewToolResultError(fmt.Sprintf("checking local data store %s: %v", path, err))
	}
	db, err := store.OpenReadOnly(path)
	if err != nil {
		return nil, mcplib.NewToolResultError(fmt.Sprintf("opening local data store %s: %v. Run assist-pp-cli workflow archive to refresh the store, or use live endpoint MCP tools for unsynced data.", path, err))
	}
	return db, nil
}

func mcpMissingStoreMessage(path string) string {
	return fmt.Sprintf("No local data store found at %s. Run assist-pp-cli workflow archive before using MCP search/sql, or use live endpoint MCP tools for unsynced data.", path)
}

func mcpStoreStatus(db *store.Store) (mcpStoreStatusKind, error) {
	status, err := db.Status()
	if err != nil {
		return "", err
	}
	if len(status) == 0 {
		return mcpStoreStatusEmpty, nil
	}
	return mcpStoreStatusReady, nil
}

func mcpEmptyStoreNextStep() string {
	return "Run assist-pp-cli workflow archive to populate the local SQLite store before using MCP search/sql."
}

func handleSearch(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	limit := 25
	if v, ok := args["limit"].(float64); ok && v > 0 {
		limit = int(v)
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	results, err := db.Search(query, limit)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("search failed: %v", err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSearchEnvelope(results, storeStatus))
}

func mcpSearchEnvelope(results []json.RawMessage, storeStatus mcpStoreStatusKind) map[string]any {
	if results == nil {
		results = []json.RawMessage{}
	}
	out := map[string]any{
		"count":        len(results),
		"results":      results,
		"store_status": storeStatus,
		"resumable":    false,
	}
	if len(results) == 0 {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "No local search matches. Try a broader query, a lower-specificity FTS expression, or sync again if data may be stale."
		}
	}
	return out
}

// validateReadOnlyQuery gates the MCP sql tool. The agent contract advertised
// to the host is ReadOnlyHintAnnotation(true); a false annotation on a
// mutating tool lets MCP hosts auto-approve writes and is treated as a real
// bug per the project's agent-native security model.
//
// The gate rejects multi-statement input, then applies an allowlist (SELECT or
// WITH only) AFTER stripping the leading whitespace, line comments, block
// comments, and semicolons that SQLite itself ignores before parsing. A naive
// HasPrefix check on a keyword blocklist is bypassable by prefixing the
// dangerous statement with "/* x */" or "-- x\n"; a naive leading-keyword
// allowlist is bypassable by appending "; ATTACH DATABASE ...". Combined with
// the empirical fact that modernc.org/sqlite's mode=ro does NOT block VACUUM
// INTO (writes a snapshot to a new file) or ATTACH DATABASE (opens a separate
// writable handle), either bypass produces silent exfiltration to an
// attacker-chosen path.
//
// SELECT and WITH are the only allowed leading keywords. WITH supports
// SELECT-form CTEs; CTE-wrapped writes ("WITH x AS (...) INSERT ...") are
// caught by OpenReadOnly's mode=ro one layer down. PRAGMA, ATTACH, VACUUM,
// and every other DDL/DML keyword fail at this gate before reaching SQLite.
func validateReadOnlyQuery(query string) error {
	stripped := stripLeadingSQLNoise(query)
	if hasTrailingSQLStatement(stripped) {
		return fmt.Errorf("only a single SELECT or WITH statement is allowed")
	}
	upper := strings.ToUpper(stripped)
	if !strings.HasPrefix(upper, "SELECT") && !strings.HasPrefix(upper, "WITH") {
		return fmt.Errorf("only SELECT queries are allowed")
	}
	return nil
}

// stripLeadingSQLNoise removes leading whitespace, SQL line comments
// (-- to end of line), block comments (/* ... */), and statement
// separators (;) from query. SQLite skips these before parsing the first
// keyword, so a security gate that does not strip them mismatches what the
// driver actually executes.
func stripLeadingSQLNoise(query string) string {
	for {
		query = strings.TrimLeft(query, " \t\r\n;")
		switch {
		case strings.HasPrefix(query, "--"):
			if idx := strings.IndexByte(query, '\n'); idx >= 0 {
				query = query[idx+1:]
				continue
			}
			return ""
		case strings.HasPrefix(query, "/*"):
			if idx := strings.Index(query[2:], "*/"); idx >= 0 {
				query = query[2+idx+2:]
				continue
			}
			return ""
		default:
			return query
		}
	}
}

// hasTrailingSQLStatement reports whether query contains a statement
// terminator followed by more executable SQL. A trailing semicolon is allowed;
// a second statement is not. Semicolons inside string literals, quoted
// identifiers, bracket identifiers, and comments are ignored to match SQLite's
// parser shape closely enough for this security gate.
func hasTrailingSQLStatement(query string) bool {
	inSingle := false
	inDouble := false
	inBacktick := false
	inBracket := false
	inLineComment := false
	inBlockComment := false

	for i := 0; i < len(query); i++ {
		ch := query[i]
		next := byte(0)
		if i+1 < len(query) {
			next = query[i+1]
		}

		switch {
		case inLineComment:
			if ch == '\n' {
				inLineComment = false
			}
			continue
		case inBlockComment:
			if ch == '*' && next == '/' {
				inBlockComment = false
				i++
			}
			continue
		case inSingle:
			if ch == '\'' {
				if next == '\'' {
					i++
					continue
				}
				inSingle = false
			}
			continue
		case inDouble:
			if ch == '"' {
				if next == '"' {
					i++
					continue
				}
				inDouble = false
			}
			continue
		case inBacktick:
			if ch == '`' {
				if next == '`' {
					i++
					continue
				}
				inBacktick = false
			}
			continue
		case inBracket:
			if ch == ']' {
				inBracket = false
			}
			continue
		}

		switch {
		case ch == '-' && next == '-':
			inLineComment = true
			i++
		case ch == '/' && next == '*':
			inBlockComment = true
			i++
		case ch == '\'':
			inSingle = true
		case ch == '"':
			inDouble = true
		case ch == '`':
			inBacktick = true
		case ch == '[':
			inBracket = true
		case ch == ';':
			if stripLeadingSQLNoise(query[i+1:]) != "" {
				return true
			}
			return false
		}
	}
	return false
}

func handleSQL(ctx context.Context, req mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	args := req.GetArguments()
	query, ok := args["query"].(string)
	if !ok || query == "" {
		return mcplib.NewToolResultError("query is required"), nil
	}

	if err := validateReadOnlyQuery(query); err != nil {
		return mcplib.NewToolResultError(err.Error()), nil
	}

	path, err := mcpDBPath()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("resolving database: %v", err)), nil
	}
	db, toolErr := openMCPReadOnlyStore(path)
	if toolErr != nil {
		return toolErr, nil
	}
	defer db.Close()

	rows, err := db.DB().QueryContext(ctx, query)
	if err != nil {
		return mcplib.NewToolResultError(mcpSQLQueryError(err)), nil
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading columns: %v", err)), nil
	}
	var results []map[string]any
	for rows.Next() {
		values := make([]any, len(cols))
		ptrs := make([]any, len(cols))
		for i := range values {
			ptrs[i] = &values[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return mcplib.NewToolResultError(fmt.Sprintf("scanning row: %v", err)), nil
		}
		row := make(map[string]any)
		for i, col := range cols {
			row[col] = values[i]
		}
		results = append(results, row)
	}
	// rows.Next() stops on a mid-iteration error without failing the loop, so
	// skipping rows.Err() would return a truncated result set as success.
	if err := rows.Err(); err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading rows: %v", err)), nil
	}
	storeStatus, err := mcpStoreStatus(db)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("reading store status: %v", err)), nil
	}

	return toolResultJSON(mcpSQLEnvelope(results, cols, storeStatus))
}

func mcpSQLEnvelope(rows []map[string]any, columns []string, storeStatus mcpStoreStatusKind) map[string]any {
	if rows == nil {
		rows = []map[string]any{}
	}
	out := map[string]any{
		"count":        len(rows),
		"columns":      columns,
		"rows":         rows,
		"store_status": storeStatus,
		"resumable":    false,
	}
	if len(rows) == 0 {
		if storeStatus == mcpStoreStatusEmpty {
			out["next_step"] = mcpEmptyStoreNextStep()
		} else {
			out["next_step"] = "The read-only SQL query returned no rows. Check resource_type filters, json_extract paths, or run sync again if data may be stale."
		}
	}
	return out
}

func mcpSQLQueryError(err error) string {
	msg := err.Error()
	if strings.Contains(strings.ToLower(msg), "no such table") {
		return fmt.Sprintf("query failed: %v. Synced records live in resources(resource_type, id, data), not one SQL table per resource. Filter by resource_type, for example resource_type='academic-years', and read JSON fields with json_extract(data,'$.field').", err)
	}
	return fmt.Sprintf("query failed: %v", err)
}

// toolResultJSON renders v as the indented JSON body of an MCP text result,
// surfacing a marshal failure as a tool error instead of empty content.
func toolResultJSON(v any) (*mcplib.CallToolResult, error) {
	text, err := bound.JSON(v)
	if err != nil {
		return mcplib.NewToolResultError(fmt.Sprintf("encoding result: %v", err)), nil
	}
	return mcplib.NewToolResultText(text), nil
}

func handleContext(_ context.Context, _ mcplib.CallToolRequest) (*mcplib.CallToolResult, error) {
	paths := map[string]string{}
	if dir, err := cliutil.ConfigDir(); err == nil {
		paths["config_dir"] = dir
	}
	if dir, err := cliutil.DataDir(); err == nil {
		paths["data_dir"] = dir
	}
	if dir, err := cliutil.StateDir(); err == nil {
		paths["state_dir"] = dir
	}
	if dir, err := cliutil.CacheDir(); err == nil {
		paths["cache_dir"] = dir
	}
	ctx := map[string]any{
		"api":         "assist",
		"description": "Anonymous access to ASSIST's public articulation and transferability endpoints.",
		"archetype":   "education-data",
		"tool_count":  10,
		"paths":       paths,
		// tool_surface tells agents which surface a capability lives on.
		"tool_surface": "MCP exposes typed endpoint tools plus a runtime mirror of user-facing CLI commands. Endpoint tools keep typed schemas; command-mirror tools shell out to the companion assist-pp-cli binary.",
		// learn_protocol is generated from the single shared source of
		// truth (the exported constant internal/learn.RecallFirstProtocol)
		// also consumed by the CLI agent-context command, so the MCP and
		// CLI agent surfaces cannot drift.
		"learn_protocol": learn.RecallFirstProtocol,
		"auth": map[string]any{
			"type":     "none",
			"env_vars": []map[string]any{},
			"docs_url": "https://assist.org",
		},
		"resources": []map[string]any{
			{
				"name":        "academic-years",
				"description": "List active ASSIST academic years and their IDs.",
				"endpoints":   []string{"list"},
			},
			{
				"name":        "agreements",
				"description": "Discover and fetch published articulation agreements.",
				"endpoints":   []string{"categories", "get", "institutions", "list"},
			},
			{
				"name":        "institutions",
				"description": "List California institutions and their historical names and identifiers.",
				"endpoints":   []string{"list"},
			},
			{
				"name":        "transferability",
				"description": "Query transferability areas and course applicability.",
				"endpoints":   []string{"years", "categories", "courses"},
			},
		},
		"query_tips": []string{
			"No API key is required; the client bootstraps an anonymous XSRF session.",
			"Use academic-years and institutions first to resolve current public IDs.",
			"Agreement list requests preserve the website's query-parameter order because the public endpoint is order-sensitive.",
		},
		// Command-mirror capabilities are exposed through MCP by shelling out
		// to the companion CLI binary.
		"command_mirror_capabilities": []map[string]string{
			{"name": "Institution and year resolver", "command": "resolve institution", "description": "Turn recognizable institution and academic-year names into exact ASSIST identifiers.", "rationale": "It deterministically correlates two official reference collections and handles missing or ambiguous matches.", "via": "mcp-command-mirror"},
			{"name": "Human-readable agreement discovery", "command": "advisor agreements", "description": "Find official agreements from institution names, catalog year, and agreement types in one call.", "rationale": "It resolves multiple IDs, verifies the published partner, and returns the official scoped agreement set.", "via": "mcp-command-mirror"},
			{"name": "Published agreement structural diff", "command": "agreements diff", "description": "Compare two official agreement payloads as deterministic added, removed, and changed JSON paths.", "rationale": "It canonicalizes and compares opaque nested agreement structures that the single-record API does not diff.", "via": "mcp-command-mirror"},
		},
		"playbook": []map[string]string{
			{"topic": "Institution and year resolver", "insight": "It deterministically correlates two official reference collections and handles missing or ambiguous matches."},
			{"topic": "Human-readable agreement discovery", "insight": "It resolves multiple IDs, verifies the published partner, and returns the official scoped agreement set."},
			{"topic": "Published agreement structural diff", "insight": "It canonicalizes and compares opaque nested agreement structures that the single-record API does not diff."},
		},
	}
	return toolResultJSON(ctx)
}

// RegisterNovelFeatureTools is kept as a compatibility no-op for older MCP
// mains. New generated mains call RegisterTools only; RegisterTools now
// includes the runtime Cobra-tree mirror.
func RegisterNovelFeatureTools(s *server.MCPServer) {
	_ = s
}
