// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

const assistAgreementsVisibleAtRoot = true

func newAgreementsCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "agreements",
		Short:       "Discover and fetch published articulation agreements.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPublicAgreementCategoriesCmd(flags))
	cmd.AddCommand(newAgreementsGetCmd(flags))
	cmd.AddCommand(newAgreementsInstitutionsCmd(flags))
	cmd.AddCommand(newAgreementsListCmd(flags))
	cmd.AddCommand(newNovelAgreementsDiffCmd(flags))
	return cmd
}
