// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

func newAgreementsDepartmentByCourseCmd(flags *rootFlags) *cobra.Command {
	var flagTermId string

	cmd := &cobra.Command{
		Use:         "department-by-course <sendingInstitutionParentId> <receivingInstitutionParentId> <courseType> <courseIdentifierParentId> <academicYearId>",
		Short:       "Find department articulations containing a course.",
		Example:     "  assist-pp-cli agreements department-by-course 110 7 receiving 289392 74 --json",
		Annotations: map[string]string{"pp:endpoint": "agreements.department-by-course", "pp:method": "GET", "pp:path": "/articulation/api/Agreements/Department/from/{sendingInstitutionParentId}/to/{receivingInstitutionParentId}/{courseType}/course/{courseIdentifierParentId}/for/{academicYearId}", "mcp:read-only": "true", "pp:happy-args": "sendingInstitutionParentId=110;receivingInstitutionParentId=7;courseType=receiving;courseIdentifierParentId=289392;academicYearId=74"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			path := "/articulation/api/Agreements/Department/from/{sendingInstitutionParentId}/to/{receivingInstitutionParentId}/{courseType}/course/{courseIdentifierParentId}/for/{academicYearId}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("sendingInstitutionParentId is required\nUsage: %s <%s>", cmd.CommandPath(), "sendingInstitutionParentId"))
			}
			path = replacePathParam(path, "sendingInstitutionParentId", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("receivingInstitutionParentId is required\nUsage: %s <%s>", cmd.CommandPath(), "receivingInstitutionParentId"))
			}
			path = replacePathParam(path, "receivingInstitutionParentId", args[1])
			if len(args) < 3 || args[2] == "" {
				return usageErr(fmt.Errorf("courseType is required\nUsage: %s <%s>", cmd.CommandPath(), "courseType"))
			}
			path = replacePathParam(path, "courseType", args[2])
			if len(args) < 4 || args[3] == "" {
				return usageErr(fmt.Errorf("courseIdentifierParentId is required\nUsage: %s <%s>", cmd.CommandPath(), "courseIdentifierParentId"))
			}
			path = replacePathParam(path, "courseIdentifierParentId", args[3])
			if len(args) < 5 || args[4] == "" {
				return usageErr(fmt.Errorf("academicYearId is required\nUsage: %s <%s>", cmd.CommandPath(), "academicYearId"))
			}
			path = replacePathParam(path, "academicYearId", args[4])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if flagTermId != "" {
				params["termId"] = formatCLIParamValue(flagTermId)
			}
			data, prov, err := resolveReadWithStrategyAndResponsePath(cmd.Context(), c, flags, "auto", "agreements", false, path, params, nil, "result", cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().StringVar(&flagTermId, "term-id", "", "Optional midyear term ID for sending-course matching.")

	return cmd
}
