// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

const assistCoursesVisibleAtRoot = true

func newCoursesCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "courses",
		Short:       "Query course records by institution, academic year, filters, or course IDs.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newCoursesByIdsCmd(flags))
	cmd.AddCommand(newCoursesListCmd(flags))
	return cmd
}
