// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// assistDepartmentsListScopedRead is a regeneration anchor for the custom
// institution/year-aware local resolver used below.
const assistDepartmentsListScopedRead = true

func newDepartmentsListCmd(flags *rootFlags) *cobra.Command {
	var flagIncludeTerminated bool

	cmd := &cobra.Command{
		Use:         "list <institutionId> <academicYearId>",
		Short:       "List departments for an institution and academic year.",
		Example:     "  assist-pp-cli departments list 110 74 --json",
		Annotations: map[string]string{"pp:endpoint": "departments.list", "pp:method": "GET", "pp:path": "/Departments/api/Institution/{institutionId}/Year/{academicYearId}", "mcp:read-only": "true", "pp:happy-args": "institutionId=110;academicYearId=74"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			path := "/Departments/api/Institution/{institutionId}/Year/{academicYearId}"
			if len(args) < 1 || args[0] == "" {
				return usageErr(fmt.Errorf("institutionId is required\nUsage: %s <%s>", cmd.CommandPath(), "institutionId"))
			}
			path = replacePathParam(path, "institutionId", args[0])
			if len(args) < 2 || args[1] == "" {
				return usageErr(fmt.Errorf("academicYearId is required\nUsage: %s <%s>", cmd.CommandPath(), "academicYearId"))
			}
			path = replacePathParam(path, "academicYearId", args[1])
			c, err := flags.newClient()
			if err != nil {
				return err
			}
			params := map[string]string{}
			if flagIncludeTerminated != false {
				params["includeTerminated"] = formatCLIParamValue(flagIncludeTerminated)
			}
			data, prov, err := resolveAssistScopedCatalogRead(cmd.Context(), c, flags, "departments", args[0], args[1], path, params, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_promoted.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				_ = json.Unmarshal(data, &countItems)
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope before passing through flags.
			// --select wins over --compact when both are set; --compact only runs when
			// no explicit fields were requested. Explicit format flags (--csv, --quiet,
			// --plain) opt out of the auto-JSON path so piped consumers that asked for
			// a non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			// For all other output modes (table, csv, plain, quiet), use the standard pipeline
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().BoolVar(&flagIncludeTerminated, "include-terminated", false, "Include departments terminated by the selected year.")

	return cmd
}
