// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"encoding/json"
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// assistPrefixesListScopedRead is a regeneration anchor for the custom
// institution/year-aware local resolver used below.
const assistPrefixesListScopedRead = true

func newPrefixesPromotedCmd(flags *rootFlags) *cobra.Command {
	var flagIncludeTerminated bool

	cmd := &cobra.Command{
		Use:         "prefixes <institutionId> <academicYearId>",
		Short:       "List course prefixes for an institution and academic year.",
		Long:        "List course prefixes for an institution and academic year.",
		Example:     "  assist-pp-cli prefixes list 110 74 --json",
		Annotations: map[string]string{"pp:endpoint": "prefixes.list", "pp:method": "GET", "pp:path": "/Prefixes/api/Institution/{institutionId}/Year/{academicYearId}", "mcp:read-only": "true", "pp:happy-args": "<institutionId>=110;<academicYearId>=74"},
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			c, err := flags.newClient()
			if err != nil {
				return err
			}

			path := "/Prefixes/api/Institution/{institutionId}/Year/{academicYearId}"
			if len(args) < 1 || args[0] == "" {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "institutionId is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "institutionId"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("institutionId is required\nUsage: %s <%s>", cmd.CommandPath(), "institutionId"))
			}
			path = replacePathParam(path, "institutionId", args[0])
			if len(args) < 2 || args[1] == "" {
				// JSON envelope: {error, usage}. Written first; the
				// usageErr return preserves exit code 2 across modes.
				if flags.asJSON {
					if printErr := printJSONFiltered(cmd.OutOrStdout(), map[string]any{
						"error": "academicYearId is required",
						"usage": fmt.Sprintf("%s <%s>", cmd.CommandPath(), "academicYearId"),
					}, flags); printErr != nil {
						return printErr
					}
				}
				return usageErr(fmt.Errorf("academicYearId is required\nUsage: %s <%s>", cmd.CommandPath(), "academicYearId"))
			}
			path = replacePathParam(path, "academicYearId", args[1])
			params := map[string]string{}
			if flagIncludeTerminated != false {
				params["includeTerminated"] = formatCLIParamValue(flagIncludeTerminated)
			}
			data, prov, err := resolveAssistScopedCatalogRead(cmd.Context(), c, flags, "prefixes", args[0], args[1], path, params, cmd.ErrOrStderr())
			if err != nil {
				return classifyAPIError(err, flags)
			}
			// Print provenance to stderr for human-facing output only.
			// Machine-format flags (--json, --csv, --compact, --quiet, --plain,
			// --select) and piped stdout suppress this line; the JSON envelope
			// already carries meta.source for those consumers.
			// SYNC: keep this gate aligned with command_endpoint.go.tmpl.
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var countItems []json.RawMessage
				if json.Unmarshal(data, &countItems) != nil {
					// Single object, not an array
					countItems = []json.RawMessage{data}
				}
				printProvenance(cmd, len(countItems), prov)
			}
			// For JSON output, wrap with provenance envelope. --select wins over
			// --compact when both are set; --compact only runs when no explicit
			// fields were requested. Explicit format flags (--csv, --quiet, --plain)
			// opt out of the auto-JSON path so piped consumers that asked for a
			// non-JSON format reach the standard pipeline below.
			if flags.asJSON || (!isTerminal(cmd.OutOrStdout()) && !flags.csv && !flags.quiet && !flags.plain) {
				filtered := data
				if flags.selectFields != "" {
					filtered = filterFields(filtered, flags.selectFields)
				} else if flags.compact {
					filtered = compactFields(filtered)
				}
				wrapped, wrapErr := wrapWithProvenance(filtered, prov)
				if wrapErr != nil {
					return wrapErr
				}
				return printOutput(cmd.OutOrStdout(), wrapped, true)
			}
			if wantsHumanTable(cmd.OutOrStdout(), flags) {
				var items []map[string]any
				if json.Unmarshal(data, &items) == nil && len(items) > 0 {
					if err := printAutoTable(cmd.OutOrStdout(), items); err != nil {
						return err
					}
					if len(items) >= 25 {
						fmt.Fprintf(os.Stderr, "\nShowing %d results. To narrow: add --limit, --json --select, or filter flags.\n", len(items))
					}
					return nil
				}
			}
			return printOutputWithFlagsMeta(cmd.OutOrStdout(), data, flags, map[string]any{"source": "live"})
		},
	}
	cmd.Flags().BoolVar(&flagIncludeTerminated, "include-terminated", false, "Include prefixes terminated by the selected year.")

	// Wire sibling endpoints and sub-resources as subcommands

	return cmd
}
