// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"
)

const assistTransferabilityVisibleAtRoot = true

func newTransferabilityCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:         "transferability",
		Short:       "Query transferability areas and course applicability.",
		Annotations: map[string]string{"mcp:read-only": "true", "pp:typed-exit-codes": "0,2"},
		RunE:        parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newPublicTransferabilityYearsCmd(flags))
	cmd.AddCommand(newPublicTransferabilityCategoriesCmd(flags))
	cmd.AddCommand(newPublicTransferabilityCoursesCmd(flags))
	return cmd
}
