// Copyright 2026 johnnyrobot and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package client

import (
	"bytes"
	"context"
	"errors"
	"io"
	"net/http"
	"net/http/httptest"
	"net/url"
	"strings"
	"testing"
	"time"
	"unicode/utf8"

	"assist-pp-cli/internal/config"
)

func TestTruncateBody(t *testing.T) {
	t.Parallel()

	const maxBytes = 4096

	cases := []struct {
		name        string
		input       []byte
		wantLen     int
		wantHasTail bool
	}{
		{"empty", nil, 0, false},
		{"under cap", []byte("hello"), 5, false},
		{"at cap", bytes.Repeat([]byte("a"), maxBytes), maxBytes, false},
		{"one over cap", bytes.Repeat([]byte("a"), maxBytes+1), maxBytes + 3, true},
		{"huge body", bytes.Repeat([]byte("a"), maxBytes*8), maxBytes + 3, true},
	}

	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			got := truncateBody(tc.input)
			if len(got) != tc.wantLen {
				t.Fatalf("len = %d, want %d", len(got), tc.wantLen)
			}
			if tc.wantHasTail && !strings.HasSuffix(got, "...") {
				t.Fatalf("want trailing %q", "...")
			}
			if !tc.wantHasTail && strings.HasSuffix(got, "...") {
				t.Fatalf("unexpected trailing %q in %q", "...", got)
			}
		})
	}
}

func TestTruncateBody_UTF8RuneAtBoundary(t *testing.T) {
	t.Parallel()

	// '€' is 3 bytes (0xE2 0x82 0xAC). Place it so the slice at byte 4096 cuts
	// mid-rune; strings.ToValidUTF8 should drop the partial rune cleanly rather
	// than emit U+FFFD or invalid UTF-8.
	prefix := strings.Repeat("a", 4094)
	body := []byte(prefix + "€" + strings.Repeat("b", 100))
	got := truncateBody(body)

	if !utf8.ValidString(got) {
		t.Fatalf("output is not valid UTF-8")
	}
	if strings.ContainsRune(got, utf8.RuneError) {
		t.Fatalf("output contains replacement rune U+FFFD")
	}
	if !strings.HasSuffix(got, "...") {
		t.Fatalf("want trailing %q", "...")
	}
	// Partial rune must be dropped, not replaced: 4094 valid bytes + "...".
	if want := 4094 + 3; len(got) != want {
		t.Fatalf("len = %d, want %d (partial rune should be dropped, not replaced)", len(got), want)
	}
}

func TestCacheKeyDelimitsSortedQueryParams(t *testing.T) {
	t.Parallel()

	c := &Client{BaseURL: "https://api.example.test"}
	collidingTwoParams := c.cacheKey("/titles", map[string]string{
		"country": "USAformat",
		"year":    "bluray",
	})
	collidingThreeParams := c.cacheKey("/titles", map[string]string{
		"country": "USA",
		"format":  "bluray",
		"year":    "",
	})
	if collidingTwoParams == collidingThreeParams {
		t.Fatalf("cache keys collided for adjacent query params: %q", collidingTwoParams)
	}

	first := c.cacheKey("/titles", map[string]string{"format": "4k", "country": "USA"})
	second := c.cacheKey("/titles", map[string]string{"country": "USA", "format": "4k"})
	if first != second {
		t.Fatalf("cache key should be deterministic regardless of map order: %q != %q", first, second)
	}
}

func TestGetWithHeadersValuesPreservesRepeatedQueryParams(t *testing.T) {
	t.Parallel()

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		got := r.URL.Query()["format"]
		if len(got) != 2 || got[0] != "blu-ray" || got[1] != "4k" {
			t.Fatalf("format query values = %#v, want [blu-ray 4k]", got)
		}
		if got := r.URL.Query().Get("country"); got != "US" {
			t.Fatalf("country = %q, want US", got)
		}
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write([]byte(`{"ok":true}`))
	}))
	t.Cleanup(server.Close)

	c := New(&config.Config{BaseURL: server.URL}, time.Second, 0)
	c.HTTPClient = server.Client()
	c.NoCache = true

	params := url.Values{
		"format":  []string{"blu-ray", "4k"},
		"country": []string{"US"},
	}
	if _, err := c.GetWithHeadersValues(context.Background(), "/titles", params, nil); err != nil {
		t.Fatalf("GetWithHeadersValues returned error: %v", err)
	}
}

func TestReadResponseBodyLimitedRejectsFixedAndChunkedOversize(t *testing.T) {
	for _, tc := range []struct {
		name   string
		length int64
	}{
		{name: "fixed", length: 5},
		{name: "chunked", length: -1},
	} {
		t.Run(tc.name, func(t *testing.T) {
			resp := &http.Response{ContentLength: tc.length, Body: io.NopCloser(strings.NewReader("12345"))}
			_, err := readResponseBodyLimited(resp, 4)
			var tooLarge *ResponseTooLargeError
			if !errors.As(err, &tooLarge) {
				t.Fatalf("error = %v, want ResponseTooLargeError", err)
			}
		})
	}
}

func TestRedirectRejectsHTTPSDowngrade(t *testing.T) {
	c := New(&config.Config{BaseURL: "https://example.test"}, time.Second, 0)
	previous, _ := http.NewRequest(http.MethodGet, "https://example.test/start", nil)
	next, _ := http.NewRequest(http.MethodGet, "http://example.test/next", nil)
	err := c.HTTPClient.CheckRedirect(next, []*http.Request{previous})
	if err == nil || !strings.Contains(err.Error(), "HTTPS to HTTP") {
		t.Fatalf("redirect error = %v", err)
	}
}

func TestRedirectAllowsOnlySameNormalizedOrigin(t *testing.T) {
	c := New(&config.Config{BaseURL: "https://example.test"}, time.Second, 0)
	previous, _ := http.NewRequest(http.MethodGet, "https://example.test/start", nil)
	same, _ := http.NewRequest(http.MethodGet, "https://example.test:443/next", nil)
	if err := c.HTTPClient.CheckRedirect(same, []*http.Request{previous}); err != nil {
		t.Fatal(err)
	}
	crossPort, _ := http.NewRequest(http.MethodGet, "https://example.test:8443/next", nil)
	if err := c.HTTPClient.CheckRedirect(crossPort, []*http.Request{previous}); err == nil || !strings.Contains(err.Error(), "cross-origin") {
		t.Fatalf("cross-port redirect error = %v, want cross-origin rejection", err)
	}
}
